<h1 style="color:red;font-size:50px;">NumPy</h1>

<p>NumPy is a Python library that stands for "Numerical Python." It provides an extensive collection of high-performance mathematical functions and multidimensional array objects. NumPy is designed to efficiently handle large datasets and perform numerical computations efficiently.

Formally, NumPy can be defined as a powerful open-source numerical computing library for Python, which provides support for large, multi-dimensional arrays and matrices, along with an extensive collection of mathematical functions to operate on these arrays. It serves as the fundamental building block for scientific computing in Python, offering high-performance numerical operations and convenient array manipulation capabilities.

In Jupyter Notebook, NumPy can be utilized by importing the library and using its functions and objects to perform various numerical computations, data manipulation, and data analysis tasks. It offers a user-friendly interface for working with arrays and matrices, allowing users to efficiently perform mathematical operations, linear algebra computations, statistical analysis, and more.

Overall, NumPy plays a crucial role in scientific computing and data analysis workflows within Jupyter Notebook, enabling users to leverage its powerful features and capabilities for efficient numerical computations and array manipulation.</p>

In [1]:
import numpy as np

<h1 style="color:blue;font-size:30px">Creating numpy array</h1>

In [2]:
a=np.array([1,2,3]) 

In [3]:
print(a) #-->vector

[1 2 3]


In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
b=np.array([[1,2,3],[4,5,6]])

In [7]:
b  #-->matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  #--> Tensor

In [9]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

<h1 style="color:orange">dtype</h1>

<p style="font-size:20px">You can specify the data type when creating a NumPy array using the dtype parameter.
    For example:</p>

In [10]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [11]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [12]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

<h1 style="color:orange">arange()</h1>

<p style="font-size:20px">In NumPy, the arange function is used to create arrays with regularly spaced values within a specified range. It returns an array containing evenly spaced values starting from a specified start value and incrementing by a specified step size.</p>

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h1 style="color:orange">reshape()</h1>

<p style="font-size:20px">In NumPy, the reshape function is used to change the shape or dimensions of an array without altering its data. It returns a new view of the original array with a different shape.

</p>

In [15]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
np.arange(1,11).reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

<h1 style="color:orange">ones() & zeros()</h1>

<p style="font-size:20px">In NumPy, the ones and zeros functions are used to create arrays filled with ones and zeros, respectively. These functions allow you to quickly generate arrays of desired shape and data type, filled with either ones or zeros.</p>

In [17]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

<h1 style="color:orange">random.rand()</h1>

<p style='font-size:20px'>np.random is a module in NumPy that provides functions for generating random numbers, random arrays, and performing random sampling. It allows you to incorporate randomness and simulate random processes in your data analysis or modeling tasks.
</p>


In [19]:
np.random.rand(3,2)

array([[0.79787339, 0.1217412 ],
       [0.9445563 , 0.06071541],
       [0.93796708, 0.26345268]])

<h1 style="color:orange">linspace()</h1>

<p style='font-size:20px'>In NumPy, the linspace function is used to create arrays with evenly spaced values between a specified start and end point, inclusive. It allows you to define the number of elements or the spacing between the values in the resulting array.</p>

In [20]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

<h1 style="color:orange">identity()</h1>

<p style="font-size:20px"> In NumPy, the identity function is used to create an identity matrix, which is a square matrix with ones on the main diagonal and zeros elsewhere. </p>

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h1 style="color:blue;font-size:30px">Attributes</h1>

In [22]:
a1=np.arange(10,dtype=np.int32)

In [23]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [24]:
a2 = np.arange(12,dtype=float).reshape(3,4)

In [25]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [26]:
a3 = np.arange(8).reshape(2,2,2)

In [27]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

<h1 style="color:orange">ndim</h1>

In [28]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


<h1 style="color:orange">shape</h1>

In [29]:
a1.shape

(10,)

In [30]:
a2.shape

(3, 4)

In [31]:
a3.shape

(2, 2, 2)

<h1 style="color:orange">size</h1>

In [32]:
 a1.size

10

In [33]:
a2.size

12

In [34]:
a3.size

8

<h1 style="color:orange">itemsize</h1>

In [35]:
a1.itemsize

4

In [36]:
a2.itemsize

8

In [37]:
a3.itemsize

8

<h1 style="color:orange">dtype</h1>

In [38]:
print(a1.dtype)

int32


In [39]:
print(a2.dtype)

float64


In [40]:
print(a3.dtype)

int64


<h1 style="color:blue;font-size:30px">Changing Datatype</h1>

<h1 style="color:orange">astype()</h1>

In [41]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

<h1 style="color:blue;font-size:30px">Array Operations</h1>

In [42]:
a1 = np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(3,4)

<h1 style="color:orange">scalar operation</h1>

In [43]:
# arithmetic (*,+,-,/,**,%) 
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [44]:
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [45]:
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [46]:
a1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [47]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [48]:
a1//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

In [49]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [50]:
#relational
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

<h1 style="color:orange">vector operation</h1>

In [52]:
#arithmetic
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

<h1 style="color:blue;font-size:30px">Array Functions</h1>

<h1 style="color:orange">round()</h1>

In [53]:
 a1 = np.random.random((3,3))

In [54]:
a1=np.round(a1*100)

In [55]:
a1

array([[77., 80., 31.],
       [70., 49., 57.],
       [51., 23., 48.]])

<h1 style="color:orange">min()</h1>

In [56]:
a1.min()

23.0

<h1 style="color:orange">sum()</h1>

In [57]:
a1.sum()

486.0

<h1 style="color:orange">max()</h1>

In [58]:
a1.max()

80.0

<h1 style="color:orange">prod()</h1>

In [59]:
np.prod(a1)

2102086732838400.0

<h1 style="color:orange">for row-wise</h1>

In [60]:
np.max(a1,axis=1) 

array([80., 70., 51.])

<h1 style="color:orange">column-wise</h1>

In [61]:
#column wise
np.max(a1,axis=0)

array([77., 80., 57.])

<h1 style="color:orange">row-wise multiplication</h1>

In [62]:
np.prod(a1,axis=1)

array([190960., 195510.,  56304.])

<h1 style="color:orange">mean()</h1>

In [63]:
np.mean(a1)

54.0

In [64]:
np.mean(a1,axis=1)

array([62.66666667, 58.66666667, 40.66666667])

<h1 style="color:orange">median()</h1>

In [65]:
np.median(a1,axis=1)

array([77., 57., 48.])

In [66]:
np.median(a1)

51.0

<h1 style="color:orange">std()</h1>

In [67]:
np.std(a1)

18.34847859269718

In [68]:
#colume WISE
np.std(a1,axis=0)

array([10.98483804, 23.29997616, 10.78064109])

<h1 style="color:blue;font-size:30px">trignometry function</h1>

<h1 style="color:orange">sin()</h1>

In [69]:
np.sin(a1)

array([[ 0.99952016, -0.99388865, -0.40403765],
       [ 0.77389068, -0.95375265,  0.43616476],
       [ 0.67022918, -0.8462204 , -0.76825466]])

<h1 style="color:orange">log()</h1>

In [70]:
np.log(a1)

array([[4.34380542, 4.38202663, 3.4339872 ],
       [4.24849524, 3.8918203 , 4.04305127],
       [3.93182563, 3.13549422, 3.87120101]])

In [71]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

<h1 style="color:orange">dot()</h1>

In [72]:
a2.dot(a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

<h1 style="color:orange">exp()</h1>

In [73]:
np.exp(a3)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

<h1 style="color:orange">round()</h1>

In [74]:
np.round(np.random.random((2,3))*100)

array([[49., 32., 67.],
       [69., 78., 56.]])

<h1 style="color:orange">floor()</h1>

In [75]:
#piche wala integer
np.floor(np.random.random((2,3))*100)

array([[31.,  7., 96.],
       [54., 16., 28.]])

<h1 style="color:orange">ceil()</h1>

In [76]:
#aage wala integer
np.ceil(np.random.random((2,3))*100)

array([[98., 83., 38.],
       [45., 87.,  9.]])

<h1 style="color:blue;font-size:30px">Indexing & Slicing</h1>

In [77]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [78]:
#right to left
a1[-1]

9

In [79]:
#left to right
a1[0]

0

In [80]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
a2[1,2]

6

In [82]:
a2[2,3]

11

In [83]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a3[1,0,1]

5

In [85]:
a3[0,1,0]

2

In [86]:
a1[2:5]

array([2, 3, 4])

In [87]:
a2[0,:]

array([0, 1, 2, 3])

In [88]:
a2[:,2]

array([ 2,  6, 10])

In [89]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [90]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [91]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [92]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [93]:
a3=np.arange(27).reshape(3,3,3)

In [94]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [95]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [96]:
a3[1][1][1]

13

In [97]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [98]:
a3[0][1,:]

array([3, 4, 5])

In [99]:
a3[0,1,:]

array([3, 4, 5])

In [100]:
a3[1,:,1]

array([10, 13, 16])

In [101]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [102]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

<h1 style="color:blue;font-size:30px">Iteration</h1>

In [103]:
a1
for i in a1:
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 

In [104]:
for i in a2:
    print(i,end=' ')

[0 1 2 3] [4 5 6 7] [ 8  9 10 11] 

In [105]:
for i in a3:
    print(i,end=' ')

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[ 9 10 11]
 [12 13 14]
 [15 16 17]] [[18 19 20]
 [21 22 23]
 [24 25 26]] 

In [106]:
for i in a3:
    for j in i:
        for k in j:
            print(k,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [107]:
for i in np.nditer(a3):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

<h1 style="color:blue;font-size:30px">Reshaping</h1>

In [108]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<h1 style="color:orange">reshape()</h1>

In [109]:
a2.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

<h1 style="color:orange">transpose</h1>

In [110]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [111]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [112]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<h1 style="color:orange">ravel()</h1>

In [113]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [114]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

<h1 style="color:blue;font-size:30px">Stacking</h1>

<h1 style="color:orange">horizontal stacking</h1>

In [115]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

<h1 style="color:orange">vertical stacking</h1>

In [116]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

<h1 style="color:blue;font-size:30px">Splitting</h1>

<h1 style="color:orange">horizontal splitting</h1>

In [117]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [119]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

<h1 style="color:orange">vertical split</h1>

In [120]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]