# Numpy

Numpy is created in C but wrap in python because python is easy syntax. 

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3]) 

In [4]:
print(a)

[1 2 3]


In [5]:
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [8]:
b=np.array([[1,2,3],[4,5,6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [12]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [15]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [16]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
np.arange(1,11).reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [25]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [30]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.random.rand(3,2)

array([[0.04503884, 0.88902003],
       [0.92758291, 0.36139353],
       [0.70397597, 0.45917003]])

In [37]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Atrributes

In [57]:
a1=np.arange(10,dtype=np.int32)

In [58]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [59]:
a2 = np.arange(12,dtype=float).reshape(3,4)

In [60]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [61]:
a3 = np.arange(8).reshape(2,2,2)

In [62]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [64]:
a1.shape

(10,)

In [65]:
a2.shape

(3, 4)

In [66]:
a3.shape

(2, 2, 2)

In [67]:
 a1.size

10

In [68]:
a2.size

12

In [69]:
a3.size

8

In [70]:
a1.itemsize

4

In [71]:
a2.itemsize

8

In [72]:
a3.itemsize

8

In [73]:
print(a1.dtype)

int32


In [74]:
print(a2.dtype)

float64


In [75]:
print(a3.dtype)

int64


# changing data type

In [76]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operation

In [97]:
a1 = np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(3,4)

In [98]:
#scalar operation
#a1(*,+,-,/,**,%)2

#relational
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [99]:
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [100]:
#vector operation
#arithmetic
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Function

In [102]:
 a1 = np.random.random((3,3))

In [103]:
a1=np.round(a1*100)

In [104]:
a1

array([[60., 31., 96.],
       [76., 65., 63.],
       [22., 74., 89.]])

In [105]:
a1.min()

22.0

In [106]:
a1.sum()

576.0

In [107]:
a1.max()

96.0

In [109]:
np.prod(a1)

8051857548134400.0

In [110]:
#for row wise
np.max(a1,axis=1) 

array([96., 76., 89.])

In [113]:
#column wise
np.max(a1,axis=0)

array([76., 74., 96.])

In [114]:
np.prod(a1,axis=1)

array([178560., 311220., 144892.])

# MIN / std / var / MEDIAN  

In [115]:
np.mean(a1)

64.0

In [118]:
np.mean(a1,axis=1)

array([62.33333333, 68.        , 61.66666667])

In [119]:
np.median(a1,axis=1)

array([60., 65., 74.])

In [120]:
np.median(a1)

65.0

In [121]:
np.std(a1)

23.007245235649865

In [122]:
#colume WISE
np.std(a1,axis=0)

array([22.64705034, 18.51725922, 14.19702629])

In [123]:
#trignometry function
np.sin(a1)

array([[-0.30481062, -0.40403765,  0.98358775],
       [ 0.56610764,  0.82682868,  0.1673557 ],
       [-0.00885131, -0.98514626,  0.86006941]])

In [124]:
np.log(a1)

array([[4.09434456, 3.4339872 , 4.56434819],
       [4.33073334, 4.17438727, 4.14313473],
       [3.09104245, 4.30406509, 4.48863637]])

In [126]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [127]:
a2.dot(a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [128]:
np.exp(a3)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

# ROUND / FLOOR / CEIL

In [129]:
np.round(np.random.random((2,3))*100)

array([[54., 59., 80.],
       [59., 61., 70.]])

In [132]:
#piche wala integer
np.floor(np.random.random((2,3))*100)

array([[39., 74., 81.],
       [73., 63., 26.]])

In [134]:
#aage wala integer
np.ceil(np.random.random((2,3))*100)

array([[ 16.,  82., 100.],
       [ 53.,  90.,  23.]])

# Indexing And Slicing

In [136]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [137]:
#right to left
a1[-1]

9

In [138]:
#left to right
a1[0]

0

In [139]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
a2[1,2]

6

In [141]:
a2[2,3]

11

In [142]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [143]:
a3[1,0,1]

5

In [145]:
a3[0,1,0]

2

In [147]:
a1[2:5]

array([2, 3, 4])

In [149]:
a2[0,:]

array([0, 1, 2, 3])

In [150]:
a2[:,2]

array([ 2,  6, 10])

In [151]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [152]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [154]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [156]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [157]:
a3=np.arange(27).reshape(3,3,3)

In [158]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [160]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [161]:
a3[1][1][1]

13

In [162]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [164]:
a3[0][1,:]

array([3, 4, 5])

In [166]:
a3[0,1,:]

array([3, 4, 5])

In [167]:
a3[1,:,1]

array([10, 13, 16])

In [168]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [170]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iteration

In [179]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [180]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [182]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [183]:
for i in a3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [187]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# 

# reshaping

In [188]:
#reshape
#transpose
#ravel
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [190]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [191]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [193]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [195]:
#horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [198]:
#vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spliting

In [199]:
#horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [201]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [202]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [203]:
#vertical split


In [204]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]