<h1 style="color:blue;font-size:30px">np.sort()</h1>

In [3]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([65, 68, 63, 24, 55, 61, 68, 73, 12, 30, 70, 10, 64, 21, 32])

In [4]:
b= np.random.randint(1,100,24).reshape(6,4)
b

array([[48, 30,  4,  3],
       [51, 26, 65, 82],
       [82, 38, 60, 67],
       [23, 36, 28, 52],
       [46, 20, 26, 58],
       [42, 59, 34, 68]])

In [5]:
np.sort(a)

array([10, 12, 21, 24, 30, 32, 55, 61, 63, 64, 65, 68, 68, 70, 73])

In [6]:
np.sort(b) ## default sorting row-wise

array([[ 3,  4, 30, 48],
       [26, 51, 65, 82],
       [38, 60, 67, 82],
       [23, 28, 36, 52],
       [20, 26, 46, 58],
       [34, 42, 59, 68]])

<h1 style="color:orange">sort function kind parameter</h1>

In [7]:
np.sort(a,kind="mergesort")

array([10, 12, 21, 24, 30, 32, 55, 61, 63, 64, 65, 68, 68, 70, 73])

<h1 style="color:orange">Column-Wise sorting</h1>

In [8]:
np.sort(b,axis=0)

array([[23, 20,  4,  3],
       [42, 26, 26, 52],
       [46, 30, 28, 58],
       [48, 36, 34, 67],
       [51, 38, 60, 68],
       [82, 59, 65, 82]])

<h1 style="color:orange">reverse sorting</h1>

In [9]:
#for reverse sorting
np.sort(a)[::-1]

array([73, 70, 68, 68, 65, 64, 63, 61, 55, 32, 30, 24, 21, 12, 10])

<h1 style="color:blue;font-size:30px">np.append()</h1>

In [10]:
a

array([65, 68, 63, 24, 55, 61, 68, 73, 12, 30, 70, 10, 64, 21, 32])

In [11]:
np.append(a,1200)

array([  65,   68,   63,   24,   55,   61,   68,   73,   12,   30,   70,
         10,   64,   21,   32, 1200])

In [12]:
b

array([[48, 30,  4,  3],
       [51, 26, 65, 82],
       [82, 38, 60, 67],
       [23, 36, 28, 52],
       [46, 20, 26, 58],
       [42, 59, 34, 68]])

In [13]:
c=np.array([1,2,3,4])
print(np.append(b,[1,2,3,4]))
print()
print(np.append(b,c))

[48 30  4  3 51 26 65 82 82 38 60 67 23 36 28 52 46 20 26 58 42 59 34 68
  1  2  3  4]

[48 30  4  3 51 26 65 82 82 38 60 67 23 36 28 52 46 20 26 58 42 59 34 68
  1  2  3  4]


In [14]:
np.ones((b.shape[0],1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [15]:
np.append(b,np.ones((b.shape[0],1)))

array([48., 30.,  4.,  3., 51., 26., 65., 82., 82., 38., 60., 67., 23.,
       36., 28., 52., 46., 20., 26., 58., 42., 59., 34., 68.,  1.,  1.,
        1.,  1.,  1.,  1.])

<h1 style="color:orange">Column-wise append</h1>

In [16]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[48., 30.,  4.,  3.,  1.],
       [51., 26., 65., 82.,  1.],
       [82., 38., 60., 67.,  1.],
       [23., 36., 28., 52.,  1.],
       [46., 20., 26., 58.,  1.],
       [42., 59., 34., 68.,  1.]])

<h1 style="color:blue;font-size:30px">np.concatenate()</h1>

In [17]:
#np.concatenate() function concatenate a sequence of array along an existing axis.

In [18]:
c= np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [19]:
np.concatenate((c,d)) #default concatenation row-wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

<h1 style="color:orange">column-wise</h1> 

In [21]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

<h1 style="color:blue;font-size:30px">np.unique()</h1>

In [22]:
e=np.unique([11,2,2,2,33,3,33,11])
np.unique(e)

array([ 2,  3, 11, 33])

<h1 style="color:blue;font-size:30px">np.expand_dims</h1>

In [23]:
a

array([65, 68, 63, 24, 55, 61, 68, 73, 12, 30, 70, 10, 64, 21, 32])

In [24]:
v=np.expand_dims(a,axis=0)
v

array([[65, 68, 63, 24, 55, 61, 68, 73, 12, 30, 70, 10, 64, 21, 32]])

In [25]:
print(a.ndim)
print()
print(v.ndim)

1

2


In [26]:
y = np.expand_dims(a,axis=1)

In [27]:
print(a.ndim)
print()
print(y.ndim)

1

2


<h1 style="color:blue;font-size:30px">np.where()</h1>

<h1 style="color:orange">find all indices with values greater than 50</h1> 

In [28]:
np.where(a>50)

(array([ 0,  1,  2,  4,  5,  6,  7, 10, 12]),)

In [29]:
c=a[a>50]
c

array([65, 68, 63, 55, 61, 68, 73, 70, 64])

<h1 style="color:orange">replace all values > 50 with 0</h1> 

In [30]:
np.where(a>50,0,a)

array([ 0,  0,  0, 24,  0,  0,  0,  0, 12, 30,  0, 10,  0, 21, 32])

<h1 style="color:orange">replace all even no's from zero</h1> 

In [31]:
print(a)
print()
np.where(a%2==0,0,a)

[65 68 63 24 55 61 68 73 12 30 70 10 64 21 32]



array([65,  0, 63,  0, 55, 61,  0, 73,  0,  0,  0,  0,  0, 21,  0])

<h1 style="color:blue;font-size:30px">np.argmax()</h1>

In [32]:
a

array([65, 68, 63, 24, 55, 61, 68, 73, 12, 30, 70, 10, 64, 21, 32])

In [33]:
print("value ",np.max(a))
print()
print("index ",np.argmax(a))

value  73

index  7


In [34]:
print(b)
print()
print(np.max(b))
print()
print(np.argmax(b))

[[48 30  4  3]
 [51 26 65 82]
 [82 38 60 67]
 [23 36 28 52]
 [46 20 26 58]
 [42 59 34 68]]

82

7


<h1 style="color:orange">column-wise</h1> 

In [35]:
np.argmax(b,axis=0)

array([2, 5, 1, 1])

<h1 style="color:orange">row-wise</h1> 

In [36]:
np.argmax(b,axis=1)

array([0, 3, 0, 3, 3, 3])

<h1 style="color:blue;font-size:30px">np.argmin()</h1>

In [37]:
print(a)
print()
print("value ",np.min(a))
print()
print("index ",np.argmin(a))

[65 68 63 24 55 61 68 73 12 30 70 10 64 21 32]

value  10

index  11


<h1 style="color:blue;font-size:30px">np.cumsum()</h1>

In [38]:
print(a)
print()
print(np.cumsum(a))

[65 68 63 24 55 61 68 73 12 30 70 10 64 21 32]

[ 65 133 196 220 275 336 404 477 489 519 589 599 663 684 716]


In [39]:
print(b)
print()
print(np.cumsum(b))

[[48 30  4  3]
 [51 26 65 82]
 [82 38 60 67]
 [23 36 28 52]
 [46 20 26 58]
 [42 59 34 68]]

[  48   78   82   85  136  162  227  309  391  429  489  556  579  615
  643  695  741  761  787  845  887  946  980 1048]


<h1 style="color:orange">column-wise</h1> 

In [41]:
print(b)
print()
print(np.cumsum(b,axis=0))

[[48 30  4  3]
 [51 26 65 82]
 [82 38 60 67]
 [23 36 28 52]
 [46 20 26 58]
 [42 59 34 68]]

[[ 48  30   4   3]
 [ 99  56  69  85]
 [181  94 129 152]
 [204 130 157 204]
 [250 150 183 262]
 [292 209 217 330]]


<h1 style="color:orange">row-wise</h1> 

In [42]:
print(b)
print()
print(np.cumsum(b,axis=1))

[[48 30  4  3]
 [51 26 65 82]
 [82 38 60 67]
 [23 36 28 52]
 [46 20 26 58]
 [42 59 34 68]]

[[ 48  78  82  85]
 [ 51  77 142 224]
 [ 82 120 180 247]
 [ 23  59  87 139]
 [ 46  66  92 150]
 [ 42 101 135 203]]


<h1 style="color:blue;font-size:30px">np.cumprod()</h1>

In [43]:
np.cumprod(a)

array([                  65,                 4420,               278460,
                    6683040,            367567200,          22421599200,
              1524668745600,      111300818428800,     1335609821145600,
          40068294634368000,  2804780624405760000, -8845681903361503232,
        5725424469859893248, -8893294648909103104, -7884267659448025088])

In [44]:
np.cumprod(b)

array([                  48,                 1440,                 5760,
                      17280,               881280,             22913280,
                 1489363200,         122127782400,       10014478156800,
            380550169958400,    22833010197504000,  1529811683232768000,
       -1707819433065439232, -6141267369227157504, -5934789674974445568,
        4985586154391207936,  7976034217480945664, -6500012313767051264,
       -2979623494557368320, -6797466020941398016, -8792411773895442432,
       -2243460595963658240, -2490683967926173696, -3345813155593846784])

<h1 style="color:blue;font-size:30px">np.percentile()</h1>

formula of percentile
:(n/N)*100

In [45]:
print(a)
print()
print(np.percentile(a,100))

[65 68 63 24 55 61 68 73 12 30 70 10 64 21 32]

73.0


In [46]:
print(np.percentile(a,50))

61.0


In [47]:
np.median(a)

61.0

<h1 style="color:blue;font-size:30px">np.histogram()</h1>

In [48]:
print(a)
print()
print(np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100]))

[65 68 63 24 55 61 68 73 12 30 70 10 64 21 32]

(array([0, 2, 2, 2, 0, 1, 6, 2, 0, 0]), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


In [49]:
print(np.histogram(a,bins=[0,50,100]))

(array([6, 9]), array([  0,  50, 100]))


<h1 style="color:blue;font-size:30px">np.corrcoef()</h1>

In [75]:
#corrcoef --> relation b/w s and e

In [50]:
s = np.array([2000,4000,25000,35000])
e= np.array([1,3,2,4])

np.corrcoef(s,e)

array([[1.        , 0.62409986],
       [0.62409986, 1.        ]])

<h1 style="color:blue;font-size:30px">np.isin()</h1>

In [51]:
#search multiple  items in single time
print(a)
print()
print("search element is 4 , 78 , 25")
i = [4,78,25]
print()
print(np.isin(a,i))
print()
print(a[np.isin(a,i)])

[65 68 63 24 55 61 68 73 12 30 70 10 64 21 32]

search element is 4 , 78 , 25

[False False False False False False False False False False False False
 False False False]

[]


<h1 style="color:blue;font-size:30px">np.flip()</h1>

In [52]:
a

array([65, 68, 63, 24, 55, 61, 68, 73, 12, 30, 70, 10, 64, 21, 32])

In [53]:
np.flip(a)

array([32, 21, 64, 10, 70, 30, 12, 73, 68, 61, 55, 24, 63, 68, 65])

In [54]:
b

array([[48, 30,  4,  3],
       [51, 26, 65, 82],
       [82, 38, 60, 67],
       [23, 36, 28, 52],
       [46, 20, 26, 58],
       [42, 59, 34, 68]])

In [55]:
#this is doing both fliping
#first row-wise then column-wise
np.flip(b)

array([[68, 34, 59, 42],
       [58, 26, 20, 46],
       [52, 28, 36, 23],
       [67, 60, 38, 82],
       [82, 65, 26, 51],
       [ 3,  4, 30, 48]])

<h1 style="color:orange">column-fliping</h1> 

In [56]:
print(b)
print()
np.flip(b,axis=0)

[[48 30  4  3]
 [51 26 65 82]
 [82 38 60 67]
 [23 36 28 52]
 [46 20 26 58]
 [42 59 34 68]]



array([[42, 59, 34, 68],
       [46, 20, 26, 58],
       [23, 36, 28, 52],
       [82, 38, 60, 67],
       [51, 26, 65, 82],
       [48, 30,  4,  3]])

<h1 style="color:orange">row-wise</h1> 

In [57]:
np.flip(b,axis=1)

array([[ 3,  4, 30, 48],
       [82, 65, 26, 51],
       [67, 60, 38, 82],
       [52, 28, 36, 23],
       [58, 26, 20, 46],
       [68, 34, 59, 42]])

<h1 style="color:blue;font-size:30px">np.put()</h1>

In [58]:
a

array([65, 68, 63, 24, 55, 61, 68, 73, 12, 30, 70, 10, 64, 21, 32])

<h1 style="color:orange">first give the array then index after that give value</h1> 

In [59]:
np.put(a,[0,1],[110,530])
a

array([110, 530,  63,  24,  55,  61,  68,  73,  12,  30,  70,  10,  64,
        21,  32])

<h1 style="color:blue;font-size:30px">np.delete()</h1>

In [60]:
a

array([110, 530,  63,  24,  55,  61,  68,  73,  12,  30,  70,  10,  64,
        21,  32])

<h1 style="color:orange">delet first item</h1> 

In [61]:
np.delete(a,0)

array([530,  63,  24,  55,  61,  68,  73,  12,  30,  70,  10,  64,  21,
        32])

In [62]:
np.delete(a,[0,4,3])

array([530,  63,  61,  68,  73,  12,  30,  70,  10,  64,  21,  32])

<h1 style="color:blue;font-size:30px">Set Functions</h1>

In [79]:
#np.union1d
#np.intersection1d
#np.setdiff1d
#np.setxor1d
#np.in1d

In [63]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
np.intersect1d(m,n)

array([3, 4, 5])

In [65]:
np.setdiff1d(m,n)

array([1, 2])

In [66]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [67]:
np.in1d(m,1)

array([ True, False, False, False, False])

<h1 style="color:blue;font-size:30px">np.clip()</h1>

In [68]:
a

array([110, 530,  63,  24,  55,  61,  68,  73,  12,  30,  70,  10,  64,
        21,  32])

In [69]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 63, 25, 55, 61, 68, 73, 25, 30, 70, 25, 64, 25, 32])