# np.sort

In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([99, 73, 80, 17, 60, 94, 69, 82, 15, 70, 91, 47, 22, 71, 94])

In [3]:
b= np.random.randint(1,100,24).reshape(6,4)
b

array([[76, 70, 93, 85],
       [89, 37, 66, 57],
       [88, 32, 76,  8],
       [75, 82, 33, 64],
       [54, 16, 13, 64],
       [10, 88, 62, 67]])

In [4]:
np.sort(a)

array([15, 17, 22, 47, 60, 69, 70, 71, 73, 80, 82, 91, 94, 94, 99])

In [5]:
np.sort(b)

array([[70, 76, 85, 93],
       [37, 57, 66, 89],
       [ 8, 32, 76, 88],
       [33, 64, 75, 82],
       [13, 16, 54, 64],
       [10, 62, 67, 88]])

In [6]:
np.sort(a,kind="mergesort")

array([15, 17, 22, 47, 60, 69, 70, 71, 73, 80, 82, 91, 94, 94, 99])

In [7]:
#column wise sorting
np.sort(b,axis=0)

array([[10, 16, 13,  8],
       [54, 32, 33, 57],
       [75, 37, 62, 64],
       [76, 70, 66, 64],
       [88, 82, 76, 67],
       [89, 88, 93, 85]])

In [8]:
#for reverse sorting
np.sort(a)[::-1]

array([99, 94, 94, 91, 82, 80, 73, 71, 70, 69, 60, 47, 22, 17, 15])

# np.append

In [9]:
a

array([99, 73, 80, 17, 60, 94, 69, 82, 15, 70, 91, 47, 22, 71, 94])

In [10]:
np.append(a,1200)

array([  99,   73,   80,   17,   60,   94,   69,   82,   15,   70,   91,
         47,   22,   71,   94, 1200])

In [11]:
b

array([[76, 70, 93, 85],
       [89, 37, 66, 57],
       [88, 32, 76,  8],
       [75, 82, 33, 64],
       [54, 16, 13, 64],
       [10, 88, 62, 67]])

In [12]:
c=np.array([1,2,3,4])
print(np.append(b,[1,2,3,4]))
print()
print(np.append(b,c))

[76 70 93 85 89 37 66 57 88 32 76  8 75 82 33 64 54 16 13 64 10 88 62 67
  1  2  3  4]

[76 70 93 85 89 37 66 57 88 32 76  8 75 82 33 64 54 16 13 64 10 88 62 67
  1  2  3  4]


In [13]:
np.ones((b.shape[0],1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [14]:
np.append(b,np.ones((b.shape[0],1)))

array([76., 70., 93., 85., 89., 37., 66., 57., 88., 32., 76.,  8., 75.,
       82., 33., 64., 54., 16., 13., 64., 10., 88., 62., 67.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [15]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[76., 70., 93., 85.,  1.],
       [89., 37., 66., 57.,  1.],
       [88., 32., 76.,  8.,  1.],
       [75., 82., 33., 64.,  1.],
       [54., 16., 13., 64.,  1.],
       [10., 88., 62., 67.,  1.]])

# np.concatenate

In [16]:
c= np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

In [20]:
e=np.unique([11,2,2,2,33,3,33,11])
np.unique(e)

array([ 2,  3, 11, 33])

np.expand_dims

In [21]:
a

array([99, 73, 80, 17, 60, 94, 69, 82, 15, 70, 91, 47, 22, 71, 94])

In [22]:
v=np.expand_dims(a,axis=0)
v

array([[99, 73, 80, 17, 60, 94, 69, 82, 15, 70, 91, 47, 22, 71, 94]])

In [23]:
print(a.ndim)
print()
print(v.ndim)

1

2


In [24]:
y = np.expand_dims(a,axis=1)

In [25]:
print(a.ndim)
print()
print(y.ndim)

1

2


# np.where

In [26]:
#find all indices with values greater than 50
np.where(a>50)

(array([ 0,  1,  2,  4,  5,  6,  7,  9, 10, 13, 14]),)

In [27]:
c=a[a>50]
c

array([99, 73, 80, 60, 94, 69, 82, 70, 91, 71, 94])

In [28]:
#replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0, 17,  0,  0,  0,  0, 15,  0,  0, 47, 22,  0,  0])

In [29]:
print(a)
print()
np.where(a%2==0,0,a)

[99 73 80 17 60 94 69 82 15 70 91 47 22 71 94]



array([99, 73,  0, 17,  0,  0, 69,  0, 15,  0, 91, 47,  0, 71,  0])

# np.argmax()

In [30]:
a

array([99, 73, 80, 17, 60, 94, 69, 82, 15, 70, 91, 47, 22, 71, 94])

In [31]:
print("value ",np.max(a))
print()
print("index ",np.argmax(a))

value  99

index  0


In [32]:
print(b)
print()
print(np.max(b))
print()
print(np.argmax(b))

[[76 70 93 85]
 [89 37 66 57]
 [88 32 76  8]
 [75 82 33 64]
 [54 16 13 64]
 [10 88 62 67]]

93

2


In [33]:
np.argmax(b,axis=0)

array([1, 5, 0, 0])

In [34]:
np.argmax(b,axis=1)

array([2, 0, 0, 1, 3, 1])

# np.argmin()

In [35]:
print(a)
print()
print("value ",np.min(a))
print()
print("index ",np.argmin(a))

[99 73 80 17 60 94 69 82 15 70 91 47 22 71 94]

value  15

index  8


# np.cumsum()

In [36]:
print(a)
print()
print(np.cumsum(a))

[99 73 80 17 60 94 69 82 15 70 91 47 22 71 94]

[ 99 172 252 269 329 423 492 574 589 659 750 797 819 890 984]


In [37]:
print(b)
print()
print(np.cumsum(b))

[[76 70 93 85]
 [89 37 66 57]
 [88 32 76  8]
 [75 82 33 64]
 [54 16 13 64]
 [10 88 62 67]]

[  76  146  239  324  413  450  516  573  661  693  769  777  852  934
  967 1031 1085 1101 1114 1178 1188 1276 1338 1405]


In [38]:
print(b)
print()
print(np.cumsum(b))

[[76 70 93 85]
 [89 37 66 57]
 [88 32 76  8]
 [75 82 33 64]
 [54 16 13 64]
 [10 88 62 67]]

[  76  146  239  324  413  450  516  573  661  693  769  777  852  934
  967 1031 1085 1101 1114 1178 1188 1276 1338 1405]


In [39]:
print(b)
print()
print(np.cumsum(b,axis=0))

[[76 70 93 85]
 [89 37 66 57]
 [88 32 76  8]
 [75 82 33 64]
 [54 16 13 64]
 [10 88 62 67]]

[[ 76  70  93  85]
 [165 107 159 142]
 [253 139 235 150]
 [328 221 268 214]
 [382 237 281 278]
 [392 325 343 345]]


In [40]:
print(b)
print()
print(np.cumsum(b,axis=1))

[[76 70 93 85]
 [89 37 66 57]
 [88 32 76  8]
 [75 82 33 64]
 [54 16 13 64]
 [10 88 62 67]]

[[ 76 146 239 324]
 [ 89 126 192 249]
 [ 88 120 196 204]
 [ 75 157 190 254]
 [ 54  70  83 147]
 [ 10  98 160 227]]


# np.cumprod

In [41]:
np.cumprod(a)

array([                  99,                 7227,               578160,
                    9828720,            589723200,          55433980800,
              3824944675200,      313645463366400,     4704681950496000,
         329327736534720000, -6924664122759583232,  6582179557071517184,
       -2766002334103034880,  6528019089489591296,  4891239979606378496])

In [42]:
np.cumprod(b)

array([                  76,                 5320,               494760,
                   42054600,           3742859400,         138485797800,
              9140062654800,      520983571323600,    45846554276476800,
        1467089736847257600,   818355558134267904,  6546844465074143232,
       -7048755109597151232, -6148852701970300928,     2045645785137152,
         130921330248777728,  7069751833433997312,  2435564892686647296,
       -5231144542492688384, -2751857392760127488, -9071829853891723264,
       -5111031972960927744, -3289333070515142656,   975613160000061440])

# np.percentile

formula of percentile
:(n/N)*100

In [43]:
print(a)
print()
print(np.percentile(a,100))

[99 73 80 17 60 94 69 82 15 70 91 47 22 71 94]

99.0


In [44]:
print(np.percentile(a,50))

71.0


In [45]:
np.median(a)

71.0

# np.histogram

In [46]:
print(a)
print()
print(np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100]))

[99 73 80 17 60 94 69 82 15 70 91 47 22 71 94]

(array([0, 2, 1, 0, 1, 0, 2, 3, 2, 4]), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


In [47]:
print(np.histogram(a,bins=[0,50,100]))

(array([ 4, 11]), array([  0,  50, 100]))


# np.corrcoef

In [48]:
s = np.array([2000,4000,25000,35000])
e= np.array([1,3,2,4])

np.corrcoef(s,e)

array([[1.        , 0.62409986],
       [0.62409986, 1.        ]])

# np.isin

In [49]:
#search multiple  items in single time
print(a)
print()
print("search element is 4 , 78 , 25")
i = [4,78,25]
print()
print(np.isin(a,i))
print()
print(a[np.isin(a,i)])

[99 73 80 17 60 94 69 82 15 70 91 47 22 71 94]

search element is 4 , 78 , 25

[False False False False False False False False False False False False
 False False False]

[]


# np.flip

In [50]:
a

array([99, 73, 80, 17, 60, 94, 69, 82, 15, 70, 91, 47, 22, 71, 94])

In [51]:
np.flip(a)

array([94, 71, 22, 47, 91, 70, 15, 82, 69, 94, 60, 17, 80, 73, 99])

In [52]:
b

array([[76, 70, 93, 85],
       [89, 37, 66, 57],
       [88, 32, 76,  8],
       [75, 82, 33, 64],
       [54, 16, 13, 64],
       [10, 88, 62, 67]])

In [53]:
#this is doing both fliping
np.flip(b)

array([[67, 62, 88, 10],
       [64, 13, 16, 54],
       [64, 33, 82, 75],
       [ 8, 76, 32, 88],
       [57, 66, 37, 89],
       [85, 93, 70, 76]])

In [54]:
#column fliping
print(b)
print()
np.flip(b,axis=0)

[[76 70 93 85]
 [89 37 66 57]
 [88 32 76  8]
 [75 82 33 64]
 [54 16 13 64]
 [10 88 62 67]]



array([[10, 88, 62, 67],
       [54, 16, 13, 64],
       [75, 82, 33, 64],
       [88, 32, 76,  8],
       [89, 37, 66, 57],
       [76, 70, 93, 85]])

In [55]:
np.flip(b,axis=1)

array([[85, 93, 70, 76],
       [57, 66, 37, 89],
       [ 8, 76, 32, 88],
       [64, 33, 82, 75],
       [64, 13, 16, 54],
       [67, 62, 88, 10]])

# np.put()

In [56]:
a

array([99, 73, 80, 17, 60, 94, 69, 82, 15, 70, 91, 47, 22, 71, 94])

In [59]:
#first give the array then index after that give value
np.put(a,[0,1],[110,530])
a

array([110, 530,  80,  17,  60,  94,  69,  82,  15,  70,  91,  47,  22,
        71,  94])

# np.delete()

In [60]:
a

array([110, 530,  80,  17,  60,  94,  69,  82,  15,  70,  91,  47,  22,
        71,  94])

In [62]:
#delete first item
np.delete(a,0)

array([530,  80,  17,  60,  94,  69,  82,  15,  70,  91,  47,  22,  71,
        94])

In [63]:
np.delete(a,[0,4,3])

array([530,  80,  94,  69,  82,  15,  70,  91,  47,  22,  71,  94])

# Set Functions

In [64]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [65]:
np.intersect1d(m,n)

array([3, 4, 5])

In [67]:
np.setdiff1d(m,n)

array([1, 2])

In [68]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [69]:
np.in1d(m,1)

array([ True, False, False, False, False])

# np.clip

In [70]:
a

array([110, 530,  80,  17,  60,  94,  69,  82,  15,  70,  91,  47,  22,
        71,  94])

In [71]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 60, 75, 69, 75, 25, 70, 75, 47, 25, 71, 75])